db:
  environment:
    POSTGRES_PASSWORD: password
  image: postgres:9.3
  restart: always
web:
  build: .
  command: python manage.py runserver 0.0.0.0:8000
  volumes:
    - .:/code
  ports:
    - "8000:8000"
  links:
    - db
  restart: always
